apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lpyp3fuef-nodejs 
  janus-idp.io/tekton: lpyp3fuef-nodejs
  backstage.io/kubernetes-id: lpyp3fuef-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lpyp3fuef-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml