apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lpyp3fuef-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lpyp3fuef-nodejs 
  name: lpyp3fuef-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: lpyp3fuef-nodejs 
